---
- name: DEBIAN - INSTALL "{{ package_deb }}" package
  become: true
  ansible.builtin.apt:
    name: "{{ package_deb }}"
    state: present
    update_cache: yes
  when: ansible_facts.packages['auditd'] is not defined
  tags:
    - auditd

- name: DEBIAN - CREATE rules.d directory
  ansible.builtin.file:
    path: "{{ auditd_config_directory }}/rules.d"
    state: directory
    mode: "0750"
  notify: Restart and enable auditd
  tags:
    - auditd

- name: DEBIAN - CONFIG main rule (audit.rules)
  ansible.builtin.template:
    src: audit.rules.j2
    dest: "{{ auditd_config_directory }}/rules.d/audit.rules"
    mode: "0600"
  notify: Restart and enable auditd
  tags:
    - auditd
