---
#- name: Display all gathered facts
#  debug:
#    var: ansible_facts
#
#- name: Display network-related facts
#  debug:
#    var: ansible_facts['ansible_interfaces']

- name: Tasks for Debian-based systems
  include_tasks: debian.yml
  when: ansible_facts['distribution_file_variety'] == "Debian"

- name: Tasks for RHEL-based systems
  include_tasks: redhat.yml
  when: ansible_facts['distribution_file_variety'] == "RedHat"



